### ISSUE TITLE
Add admin querying for backend

### ISSUE THREAD

**Issue by OutdatedGuy** [OutdatedGuy/PBL-Code#1]
The admin page is almost completed with the only thing remaining is validating admin-login.

From admin page, 4 different API requests are made.
1. /api/query/user
2. /api/query/driver
3. /api/query/trip
4. /api/query/custom

Check the incoming params in the backend for each api and develop your suitable logic.

Responded data should be like this if successful...
![image](https://user-images.githubusercontent.com/74326345/143275772-ab067864-7bee-42b3-aa23-d9ca72a541ed.png)

If after querying no data is present, respond by keeping the properties and values array in data empty.

In case of failure, copy the responded data from another API's
e.g. /api/userRegistration

**Comment by malivinayak** [comment]
I am on it
