### ISSUE TITLE
Adding login api for user-driver

### ISSUE THREAD

**Issue by OutdatedGuy** [OutdatedGuy/PBL-Code#2]
Frontend of login page for user-driver is completed.
Now only backend is remaining.

### Steps to do:-
1. Implement an api of path "/api/login/user-driver"
2. Copy the adminLogin function into a new file user_driverLogin
3. Change the function name accordingly
4. console.log data from req.body and see the sent data
5. Change query according to sent data (i.e. table names)

**Comment by OutdatedGuy** [comment]
Don't worry..
I implemented a single api for all login now

**Comment by malivinayak** [comment]
Yes, I just went through it
Working really great
token generated successfully and updated to database too
database is modified for accepting and storing the token values
![Databse updated](https://user-images.githubusercontent.com/66154908/144277033-42901c90-e8ba-4558-a86f-1b801f579897.jpg)

Really Great Work @OutdatedGuy
