### ISSUE TITLE
Adding api to book trip

### ISSUE THREAD

**Issue by OutdatedGuy** [OutdatedGuy/PBL-Code#3]
# Frontend of user page is completed.
### Steps to do:-
1. Implement an api of path "/api/trip/booking" in index.js
2. Create a file in "./routes/trip/" named "bookingTrip.js"
3. Create a function of same name as file name.
4. console.log data from req.body and see the sent data
5. Add whatever logic to randomly select a driver
6. Add all the final data in the trip table
7. Send response as:-
```js
return res.send({
  message: "Trip Booked Successfully...",
  status: "success",
  code: 200,
  data: {
    tripId: "String or int",
  },
});
```
8. For failure or fields not provided, refer other api function like userRegistration

**Comment by malivinayak** [comment]
I am working on this but it takes time as currently database for taxi, owner,.. is not ready
Till now modification of database(i.e. changing of variable names, modifying data type as per frontend req.body required, passing foreign keys and validating tokens) is done up to 50-60% and after that database must be updated with lots of data as per driver data which will take some time
so...
As soon as database is updated I will start working on APIs

**Comment by OutdatedGuy** [comment]
> 

Let's arrange a meet, so we can finalize the variable names and check the code too

**Comment by malivinayak** [comment]
Done now
