### ISSUE TITLE
Adding get trip history api

### ISSUE THREAD

**Issue by OutdatedGuy** [OutdatedGuy/PBL-Code#4]
# Frontend of user page and driver page is completed.
### Steps to do:-
1. Implement an api of path "/api/trip/history/:role" in index.js
2. The role variable can either be user or driver.
3. Refer login, credentials or session-end api functions to understand how to use it
4. Create a file in "./routes/trip/" named "history.js"
5. Create a function of same name as file name.
6. console.log data from req.body and see the sent data
7. A token is sent. Use it and the role variable to find the user/driver id by implementing your own logic
8. Depending upon the role, match the trip table data when the id of that role is present
9. Refer customQuery, driverQuery or userQuery functions for getting data
10. Send response as:-
```js
return res.send({
  status: "success",
  code: 200,
  data: {
    properties: Array,
    values: Array,
  },
});
```
11. For failure or fields not provided, refer other api function like userQuery

**Comment by malivinayak** [comment]
Done👍👍👍👍👍👍👍
